-- Global icon definitions
-- Usage: Icons.diagnostic.error, Icons.git.added, etc.

Icons = {}

Icons.diagnostic = {
  error = "e",
  warn = "w",
  info = "i",
  hint = "h",
}

Icons.folder = {
  open = "#",
  closed = "@",
  empty = "%",
}

Icons.git = {
  added = "+",
  modified = "~",
  deleted = "-",
  renamed = ">",
  untracked = "ut",
  ignored = "!",
  unstaged = "us",
  unmerged = "um",
  staged = "s",
  commit = "c",
  conflict = "x",
}

Icons.ai = {
  copilot = "Copilot",
}

Icons.cmd = {
  prompt = ">",
}

Icons.code = {
  Array = "",
  BlockMappingPair = "",
  Boolean = "",
  BreakStatement = "",
  Call = "",
  CaseStatement = "",
  Class = "",
  Codeium = "",
  Color = "",
  Collapsed = "",
  Constant = "",
  Constructor = "",
  ContinueStatement = "",
  Copilot = "",
  Declaration = "",
  Delete = "",
  DoStatement = "",
  Element = "",
  Enum = "",
  EnumMember = "",
  Event = "",
  Field = "",
  File = "",
  Folder = "",
  ForStatement = "",
  Function = "",
  GotoStatement = "",
  H1Marker = "",
  H2Marker = "",
  H3Marker = "",
  H4Marker = "",
  H5Marker = "",
  H6Marker = "",
  Identifier = "",
  IfStatement = "",
  Interface = "",
  Key = "",
  Keyword = "",
  List = "",
  Log = "",
  Lsp = "",
  Macro = "",
  MarkdownH1 = "",
  MarkdownH2 = "",
  MarkdownH3 = "",
  MarkdownH4 = "",
  MarkdownH5 = "",
  MarkdownH6 = "",
  Method = "",
  Module = "",
  Namespace = "",
  Null = "",
  Number = "",
  Object = "",
  Operator = "",
  Package = "",
  Pair = "",
  Property = "",
  Reference = "",
  Regex = "",
  Repeat = "",
  Return = "",
  RuleSet = "",
  Scope = "",
  Snippet = "",
  Specifier = "",
  Statement = "",
  String = "",
  Struct = "",
  Supermave = "",
  SwitchStatement = "",
  Table = "",
  TabNine = "",
  Terminal = "",
  Text = "",
  Type = "",
  TypeParameter = "",
  Unit = "",
  Value = "",
  Variable = "",
  WhileStatement = "",
}
