theme = "catppuccin_frappe"

[editor]
line-number = "relative"
scroll-lines = 1
cursorline = true
true-color = true
bufferline = "multiple"
auto-save = true

[editor.cursor-shape]
insert = "bar"
select = "underline"
normal = "block"

[editor.indent-guides]
render = true

[editor.file-picker]
hidden = false

[editor.lsp]
display-messages = true
display-inlay-hints = true

[editor.statusline]
left = ["mode", "spinner", "version-control"]
center = ["file-name"]
right = ["diagnostics", "file-encoding", "file-type"]
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"

[keys.normal]
F4 = ":set whitespace.render all"
F5 = ":set whitespace.render none"
C-j = ["extend_to_line_bounds", "delete_selection", "paste_after"]
C-k = ["extend_to_line_bounds", "delete_selection", "move_line_up", "paste_before"]
"C-;" = ["insert_at_line_end", ":insert-output echo ';'", "normal_mode", "move_visual_line_down"]

[keys.normal."+"]
b = ":run-shell-command cargo build"
c = ":run-shell-command cargo check"
t = ":run-shell-command cargo test"
r = ":run-shell-command cargo run"

[keys.insert]
"C-;" = ["normal_mode", "insert_at_line_end", ":insert-output echo ';'", "normal_mode", "move_visual_line_down", "insert_mode"]
