theme = "catppuccin_frappe"

[editor]
line-number = "relative"
scroll-lines = 1
cursorline = true
undercurl = true
# bufferline = "multiple"
mouse = false
color-modes = true

[editor.cursor-shape]
insert = "bar"
select = "underline"
normal = "block"

[editor.indent-guides]
render = true

[editor.file-picker]
hidden = false

[editor.lsp]
display-messages = true
display-inlay-hints = true

[editor.statusline]
left = ["mode", "spinner", "version-control"]
center = ["file-modification-indicator", "file-name", "read-only-indicator"]
right = ["position", "total-line-numbers", "register", "diagnostics", "file-encoding", "file-type"]
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"

[editor.auto-save]
after-delay.enable = true

[keys.normal]
A-j = ["extend_to_line_bounds", "delete_selection", "paste_after"]
A-k = ["extend_to_line_bounds", "delete_selection", "move_line_up", "paste_before"]
C-g = [":new", ":insert-output lazygit", ":buffer-close!", ":redraw"]

[keys.insert]
j = { k = "normal_mode" }
# C-h = "move_char_left"
# C-l = "move_char_right"
# C-o = ["normal_mode", "open_below"]
