[[language]]
name = "json"
formatter = { command = "prettier", args = ["--parser", "json", "--tab-with", "2"] }

[[language]]
name = "yaml"
auto-format = true
formatter = { command = "prettier", args = ["--parser", "yaml", "--tab-width", "2"] }

[[language]]
name = "toml"
auto-format = true
formatter = { command = "prettier", args = ["--parser", "toml", "--tab-width", "2"] }

[[language]]
name = "fish"
formatter = { command = "fish_indent" }
auto-format = true

[[language]]
name = "python"
formatter = { command = "black", args = ["--quiet", "-"] }
auto-format = true

[[language]]
name = "rust"
formatter = { command = "rustfmt" }

[language.config.check]
command = "clippy"

[language.config.pylsp.plugins]
ruff = { enabled = true, ignore = ["F401"], lineLength = 120 }

[[language]]
name = "hcl"
formatter = { command = 'terraform', args = ["fmt", "-"] }
auto-format = true

[[language]]
name = "tfvars"
formatter = { command = 'terraform', args = ["fmt", "-"] }
auto-format = true
