gui:
  sidePanelWidth: 0.2
  # catppuccin frappe theme
  # https://github.com/catppuccin/lazygit
  theme:
    activeBorderColor:
      - "#ef9f76"
      - bold
    inactiveBorderColor:
      - "#a5adce"
    optionsTextColor:
      - "#8caaee"
    selectedLineBgColor:
      - "#414559"
    cherryPickedCommitBgColor:
      - "#51576d"
    cherryPickedCommitFgColor:
      - "#ef9f76"
    unstagedChangesColor:
      - "#e78284"
    defaultFgColor:
      - "#c6d0f5"
    searchingActiveBorderColor:
      - "#e5c890"
  authorColors:
    "*": "#babbf1"

git:
  paging:
    # colorArg: never
    # pager: ydiff -p cat -s --wrap --width={{columnWidth}}
    externalDiffCommand: difft --color=always
