
# tap repositories and their packages

tap homebrew/core
brew awscli
brew basedpyright
brew bat
brew broot
brew brotli
brew buf
brew c-ares
brew ca-certificates
brew certifi
brew cmake
brew dotnet@8
brew expat
brew eza
brew fd
brew fish
brew fzf
brew gettext
brew gh
brew git
brew go
brew go-task
brew golang-migrate
brew golangci-lint
brew helix
brew helm
brew httpie
brew icu4c@77
brew jenv
brew jq
brew k9s
brew kind
brew krb5
brew kubectx
brew kubernetes-cli
brew kustomize
brew lazygit
brew lf
brew libevent
brew libgit2
brew libidn2
brew libnghttp2
brew libnghttp3
brew libngtcp2
brew libpq
brew libssh2
brew libunistring
brew libuv
brew libxau
brew libxcb
brew libxdmcp
brew libyaml
brew llvm
brew lpeg
brew luajit
brew luv
brew lz4
brew markdown-oxide
brew marksman
brew mdbook
brew mpdecimal
brew ncurses
brew neovim --HEAD
brew node
brew oniguruma
brew openssl@3
brew pcre2
brew pipx
brew pkgconf
brew pkl
brew pre-commit
brew prettier
brew python-lsp-server
brew python@3.13
brew python@3.14
brew readline
brew ripgrep
brew ruff
brew simdjson
brew sqlite
brew starship
brew taplo
brew tmux
brew tree-sitter
brew unibilium
brew utf8proc
brew uv
brew uvwasi
brew vscode-langservers-extracted
brew wget
brew xorgproto
brew xz
brew yaml-language-server
brew yazi
brew yq
brew z3
brew zellij
brew zk
brew zoxide
brew zstd

tap homebrew/cask
cask 1password
cask alacritty
cask chatgpt
cask datagrip
cask docker
cask dropbox
cask firefox
cask goland
cask intellij-idea
cask kitty
cask logseq
cask notion
cask postman
cask pycharm
cask rustrover
cask slack
cask spotify
cask via
cask zed

tap bufbuild/buf

tap koekeishiya/formulae
brew skhd
brew yabai

tap nikitabobko/tap

tap rcmdnk/file
brew brew-file

# Other Homebrew packages
brew codex

# App Store applications
appstore 409183694 Keynote (14.4)
appstore 409203825 Numbers (14.4)
appstore 409201541 Pages (14.4)
