vsync = false
neovide_refresh_rate = 120

[font]
size = 16

[font.normal]
family = "MonoLisaTrial Nerd Font"

[font.features]
"MonoLisaTrial Nerd Font" = [
  "+calt",
  "+dlig",
  "+ss01",
  "+ss02",
  "+ss03",
  "+ss04",
  "+ss05",
  "+ss06",
  "+ss07",
  "+ss08"
]
