return {
  "folke/trouble.nvim",
  opts = {
    icons = {
      indent = {
        top = " ",
        middle = " ",
        last = " ",
        fold_open = "d ",
        fold_closed = "D ",
        ws = "│  ",
      },
      folder_closed = "D ",
      folder_open = "d ",
      kinds = {
        Array = "",
        Boolean = "",
        Class = "",
        Constant = "",
        Constructor = "",
        Enum = "",
        EnumMember = "",
        Event = "",
        Field = "",
        File = "",
        Function = "",
        Interface = "",
        Key = "",
        Method = "",
        Module = "",
        Namespace = "",
        Null = "",
        Number = "",
        Object = "",
        Operator = "",
        Package = "",
        Property = "",
        String = "",
        Struct = "",
        TypeParameter = "",
        Variable = "",
      },
    },
  },
}
